Property/application/models/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from .auth import accounts

Property/application/models/accounts.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

#  @ file : accounts.py
#  @ time : 2016/8/1 13:52
#  @ author : Patrick Wang

from .. import db_property
from werkzeug.security import generate_password_hash, check_password_hash


class Accounts(db_property.Model):

    __tablename__ = 'accounts'

    id = db_property.Column(db_property.Integer, primary_key=True)
    username = db_property.Column(db_property.String(20), unique=True)
    nickname = db_property.Column(db_property.String(20))

    pwd = db_property.Column(db_property.String(128))

    role = db_property.Column(db_property.String(18))
    dept = db_property.Column(db_property.String(100))

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.pwd = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pwd, password)

    def __init__(self, username, password, nickname=None, role=None, dept=None):
        self.username = username
        self.password = password
        self.nickname = nickname
        self.dept = dept
        self.role = role

    def __repr__(self):
        return '<Accounts %r>' % self.username

Property/application/forms/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from .auth import accounts

Property/application/__init__.py
#!/usr/bin/env python
# coding=utf-8

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from config import load_config
from flask_moment import Moment


bootstrap = Bootstrap()
db_property = SQLAlchemy()
mail = Mail()
moment = Moment()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth_blueprint.user_login'


def create_app():
    # init Flask
    app = Flask(__name__)

    # init ext of Flask
    bootstrap.init_app(app)
    login_manager.init_app(app)
    db_property.init_app(app)
    mail.init_app(app)
    moment.init_app(app)

    # Load config
    config = load_config()
    app.config.from_object(config)

    from application.views.auth.account import blueprint as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from application.views.index import blueprint as index_blueprint
    app.register_blueprint(index_blueprint)

    from application.views.pages import blueprint as pages_blueprint
    app.register_blueprint(pages_blueprint)

    return app

Property/application/common/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

#  @ file : __init__.py.py
#  @ time : 2016/8/2 13:44
#  @ author : Patrick Wang

from . import decorators, email

Property/application/views/__init__.py
#!/usr/bin/env python
# coding=utf-8

from . import auth

Property/application/views/index.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

#  @ file : index.py
#  @ time : 2016/8/2 13:52
#  @ author : Patrick Wang

from flask import Blueprint, render_template
from .. import db_property
from ..models.auth.accounts import Accounts
from ..models.auth.roles import Role
from flask_login import login_required

blueprint = Blueprint('index_blueprint', __name__)


@blueprint.route('/')
def index():
    return render_template('index.html')


@blueprint.route('/createDB')
def create_db():
    db_property.create_all()
    account = Accounts(username='wangxin', email='18624020715@163.com',
                       password='123456', nickname='patrick', location='shenyang', about_me='about me', confirmed=1)
    account2 = Accounts(username='wangxin2', email='wangxin229@163.com',
                       password='123456', nickname='patrick', location='shenyang', about_me='about me', confirmed=1)
    db_property.session.add(account)
    db_property.session.add(account2)
    db_property.session.commit()

    Role.insert_roles()
    return render_template('index.html')


@blueprint.route('/secret')
@login_required
def secret():
    return 'Must logged in user can view this page'

Property/application/views/pages/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

#  @ file : __init__.py.py
#  @ time : 2016/8/5 15:53
#  @ author : Patrick Wang

from flask import Blueprint

blueprint = Blueprint('pages_blueprint', __name__)

from . import admin, functions, profile

Property/config/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

#  @ file : __init__.py
#  @ time : 2016/7/21 0:40
#  @ author : Patrick Wang

import os


def load_config():
    """加载配置项"""
    mode = os.environ.get('FLASK_MODE')

    try:
        if mode == 'PRODUCTION':
            from .production import ProductionConfig
            return ProductionConfig
        elif mode == 'TESTING':
            from .testing import TestingConfig
            return TestingConfig
        else:
            from .development import DevelopmentConfig
            return DevelopmentConfig
    except ImportError:
        from .default import DefaultConfig
        return DefaultConfig

Property/application/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Property Management{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">

{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('index_blueprint.index') }}">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('index_blueprint.index') }}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth_blueprint.user_logout') }}">Log Out</a></li>
                {% else %}
                <li><a href="{{ url_for('auth_blueprint.user_login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}
    {% endblock %}

</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{{ moment.lang("zh-CN") }}
{% endblock %}

Property/application/templates/index.html
{% extends "base.html" %}

{% block title %}Property Management{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
</div>
{% endblock %}

Property/application/templates/pages/profile.html
{% extends "base.html" %}

{% block title %}Property - {{ account.username }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>{{ account.username }}</h1>
    {% if account.name or account.location %}
    <p>
        {% if account.name %}{{ account.name }}{% endif %}
        {% if account.location %}
            From <a href="http://maps.google.com/?q={{ account.location }}">{{ account.location }}</a>
        {% endif %}
    </p>
    {% endif %}
    {% if current_user.is_admin() %}
    <p><a href="mailto:{{ account.email }}">{{ account.email }}</a></p>
    {% endif %}
    {% if account.about_me %}<p>{{ account.about_me }}</p>{% endif %}
    <p>Member since {{ moment(account.member_since).format('L') }}. Last seen {{ moment(account.last_seen).fromNow() }}.</p>
</div>
{% endblock %}

Property/application/templates/pages/profile_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Property Management - Edit profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(edit_form) }}
</div>
{% endblock %}